import 'package:pra_s_application2/presentation/android_small_three_screen/android_small_three_screen.dart';
import 'package:pra_s_application2/presentation/android_small_three_screen/binding/android_small_three_binding.dart';
import 'package:pra_s_application2/presentation/guest_board_without_registration_screen/guest_board_without_registration_screen.dart';
import 'package:pra_s_application2/presentation/guest_board_without_registration_screen/binding/guest_board_without_registration_binding.dart';
import 'package:pra_s_application2/presentation/notification_screen/notification_screen.dart';
import 'package:pra_s_application2/presentation/notification_screen/binding/notification_binding.dart';
import 'package:pra_s_application2/presentation/guest_merchant_dashboard_with_upgrade_banner_screen/guest_merchant_dashboard_with_upgrade_banner_screen.dart';
import 'package:pra_s_application2/presentation/guest_merchant_dashboard_with_upgrade_banner_screen/binding/guest_merchant_dashboard_with_upgrade_banner_binding.dart';
import 'package:pra_s_application2/presentation/guest_merchant_dashboard_with_live_services_one_screen/guest_merchant_dashboard_with_live_services_one_screen.dart';
import 'package:pra_s_application2/presentation/guest_merchant_dashboard_with_live_services_one_screen/binding/guest_merchant_dashboard_with_live_services_one_binding.dart';
import 'package:pra_s_application2/presentation/guest_merchant_dashboard_with_upgrade_banner_one_container_screen/guest_merchant_dashboard_with_upgrade_banner_one_container_screen.dart';
import 'package:pra_s_application2/presentation/guest_merchant_dashboard_with_upgrade_banner_one_container_screen/binding/guest_merchant_dashboard_with_upgrade_banner_one_container_binding.dart';
import 'package:pra_s_application2/presentation/guest_merchant_dashboard_with_live_services_screen/guest_merchant_dashboard_with_live_services_screen.dart';
import 'package:pra_s_application2/presentation/guest_merchant_dashboard_with_live_services_screen/binding/guest_merchant_dashboard_with_live_services_binding.dart';
import 'package:pra_s_application2/presentation/guest_dashboard_one_screen/guest_dashboard_one_screen.dart';
import 'package:pra_s_application2/presentation/guest_dashboard_one_screen/binding/guest_dashboard_one_binding.dart';
import 'package:pra_s_application2/presentation/guest_dashboard_screen/guest_dashboard_screen.dart';
import 'package:pra_s_application2/presentation/guest_dashboard_screen/binding/guest_dashboard_binding.dart';
import 'package:pra_s_application2/presentation/notification_one_screen/notification_one_screen.dart';
import 'package:pra_s_application2/presentation/notification_one_screen/binding/notification_one_binding.dart';
import 'package:pra_s_application2/presentation/guest_profile_2_accounts_screen/guest_profile_2_accounts_screen.dart';
import 'package:pra_s_application2/presentation/guest_profile_2_accounts_screen/binding/guest_profile_2_accounts_binding.dart';
import 'package:pra_s_application2/presentation/loan_services_screen/loan_services_screen.dart';
import 'package:pra_s_application2/presentation/loan_services_screen/binding/loan_services_binding.dart';
import 'package:pra_s_application2/presentation/my_business_card_screen/my_business_card_screen.dart';
import 'package:pra_s_application2/presentation/my_business_card_screen/binding/my_business_card_binding.dart';
import 'package:pra_s_application2/presentation/my_business_card_edit_screen/my_business_card_edit_screen.dart';
import 'package:pra_s_application2/presentation/my_business_card_edit_screen/binding/my_business_card_edit_binding.dart';
import 'package:pra_s_application2/presentation/my_business_card_saved_changes_screen/my_business_card_saved_changes_screen.dart';
import 'package:pra_s_application2/presentation/my_business_card_saved_changes_screen/binding/my_business_card_saved_changes_binding.dart';
import 'package:pra_s_application2/presentation/my_business_card_background_screen/my_business_card_background_screen.dart';
import 'package:pra_s_application2/presentation/my_business_card_background_screen/binding/my_business_card_background_binding.dart';
import 'package:pra_s_application2/presentation/principle_details_chnage_address_screen/principle_details_chnage_address_screen.dart';
import 'package:pra_s_application2/presentation/principle_details_chnage_address_screen/binding/principle_details_chnage_address_binding.dart';
import 'package:pra_s_application2/presentation/addhar_details_added_screen/addhar_details_added_screen.dart';
import 'package:pra_s_application2/presentation/addhar_details_added_screen/binding/addhar_details_added_binding.dart';
import 'package:pra_s_application2/presentation/error_screen/error_screen.dart';
import 'package:pra_s_application2/presentation/error_screen/binding/error_binding.dart';
import 'package:pra_s_application2/presentation/product_selection_screen/product_selection_screen.dart';
import 'package:pra_s_application2/presentation/product_selection_screen/binding/product_selection_binding.dart';
import 'package:pra_s_application2/presentation/current_a_c_product_selected_screen/current_a_c_product_selected_screen.dart';
import 'package:pra_s_application2/presentation/current_a_c_product_selected_screen/binding/current_a_c_product_selected_binding.dart';
import 'package:pra_s_application2/presentation/od_product_selected_screen/od_product_selected_screen.dart';
import 'package:pra_s_application2/presentation/od_product_selected_screen/binding/od_product_selected_binding.dart';
import 'package:pra_s_application2/presentation/pos_device_product_selected_screen/pos_device_product_selected_screen.dart';
import 'package:pra_s_application2/presentation/pos_device_product_selected_screen/binding/pos_device_product_selected_binding.dart';
import 'package:pra_s_application2/presentation/complete_suit_product_selected_screen/complete_suit_product_selected_screen.dart';
import 'package:pra_s_application2/presentation/complete_suit_product_selected_screen/binding/complete_suit_product_selected_binding.dart';
import 'package:pra_s_application2/presentation/k25_screen/k25_screen.dart';
import 'package:pra_s_application2/presentation/k25_screen/binding/k25_binding.dart';
import 'package:pra_s_application2/presentation/set_upi_one_screen/set_upi_one_screen.dart';
import 'package:pra_s_application2/presentation/set_upi_one_screen/binding/set_upi_one_binding.dart';
import 'package:pra_s_application2/presentation/set_upi_valid_screen/set_upi_valid_screen.dart';
import 'package:pra_s_application2/presentation/set_upi_valid_screen/binding/set_upi_valid_binding.dart';
import 'package:pra_s_application2/presentation/set_upi_invalid_screen/set_upi_invalid_screen.dart';
import 'package:pra_s_application2/presentation/set_upi_invalid_screen/binding/set_upi_invalid_binding.dart';
import 'package:pra_s_application2/presentation/set_upi_two_screen/set_upi_two_screen.dart';
import 'package:pra_s_application2/presentation/set_upi_two_screen/binding/set_upi_two_binding.dart';
import 'package:pra_s_application2/presentation/scan_qr_code_screen/scan_qr_code_screen.dart';
import 'package:pra_s_application2/presentation/scan_qr_code_screen/binding/scan_qr_code_binding.dart';
import 'package:pra_s_application2/presentation/set_upi_three_screen/set_upi_three_screen.dart';
import 'package:pra_s_application2/presentation/set_upi_three_screen/binding/set_upi_three_binding.dart';
import 'package:pra_s_application2/presentation/upi_details_added_screen/upi_details_added_screen.dart';
import 'package:pra_s_application2/presentation/upi_details_added_screen/binding/upi_details_added_binding.dart';
import 'package:pra_s_application2/presentation/enter_account_details_other_banks_screen/enter_account_details_other_banks_screen.dart';
import 'package:pra_s_application2/presentation/enter_account_details_other_banks_screen/binding/enter_account_details_other_banks_binding.dart';
import 'package:pra_s_application2/presentation/account_details_added_other_banks_screen/account_details_added_other_banks_screen.dart';
import 'package:pra_s_application2/presentation/account_details_added_other_banks_screen/binding/account_details_added_other_banks_binding.dart';
import 'package:pra_s_application2/presentation/verify_mobile_no_screen/verify_mobile_no_screen.dart';
import 'package:pra_s_application2/presentation/verify_mobile_no_screen/binding/verify_mobile_no_binding.dart';
import 'package:pra_s_application2/presentation/verifying_mobile_one_screen/verifying_mobile_one_screen.dart';
import 'package:pra_s_application2/presentation/verifying_mobile_one_screen/binding/verifying_mobile_one_binding.dart';
import 'package:pra_s_application2/presentation/verifying_mobile_screen/verifying_mobile_screen.dart';
import 'package:pra_s_application2/presentation/verifying_mobile_screen/binding/verifying_mobile_binding.dart';
import 'package:pra_s_application2/presentation/verifying_mobile_two_screen/verifying_mobile_two_screen.dart';
import 'package:pra_s_application2/presentation/verifying_mobile_two_screen/binding/verifying_mobile_two_binding.dart';
import 'package:pra_s_application2/presentation/mpin_screen/mpin_screen.dart';
import 'package:pra_s_application2/presentation/mpin_screen/binding/mpin_binding.dart';
import 'package:pra_s_application2/presentation/mpin_set_screen/mpin_set_screen.dart';
import 'package:pra_s_application2/presentation/mpin_set_screen/binding/mpin_set_binding.dart';
import 'package:pra_s_application2/presentation/select_account_type_screen/select_account_type_screen.dart';
import 'package:pra_s_application2/presentation/select_account_type_screen/binding/select_account_type_binding.dart';
import 'package:pra_s_application2/presentation/account_verifing_one_screen/account_verifing_one_screen.dart';
import 'package:pra_s_application2/presentation/account_verifing_one_screen/binding/account_verifing_one_binding.dart';
import 'package:pra_s_application2/presentation/account_verifing_screen/account_verifing_screen.dart';
import 'package:pra_s_application2/presentation/account_verifing_screen/binding/account_verifing_binding.dart';
import 'package:pra_s_application2/presentation/account_verified_screen/account_verified_screen.dart';
import 'package:pra_s_application2/presentation/account_verified_screen/binding/account_verified_binding.dart';
import 'package:pra_s_application2/presentation/account_found_screen/account_found_screen.dart';
import 'package:pra_s_application2/presentation/account_found_screen/binding/account_found_binding.dart';
import 'package:pra_s_application2/presentation/account_details_added_screen/account_details_added_screen.dart';
import 'package:pra_s_application2/presentation/account_details_added_screen/binding/account_details_added_binding.dart';
import 'package:pra_s_application2/presentation/guest_landing_page_screen/guest_landing_page_screen.dart';
import 'package:pra_s_application2/presentation/guest_landing_page_screen/binding/guest_landing_page_binding.dart';
import 'package:pra_s_application2/presentation/business_details_individual_screen/business_details_individual_screen.dart';
import 'package:pra_s_application2/presentation/business_details_individual_screen/binding/business_details_individual_binding.dart';
import 'package:pra_s_application2/presentation/scan_qr_screen/scan_qr_screen.dart';
import 'package:pra_s_application2/presentation/scan_qr_screen/binding/scan_qr_binding.dart';
import 'package:pra_s_application2/presentation/business_details_sole_proprietor_screen/business_details_sole_proprietor_screen.dart';
import 'package:pra_s_application2/presentation/business_details_sole_proprietor_screen/binding/business_details_sole_proprietor_binding.dart';
import 'package:pra_s_application2/presentation/business_details_private_limited_five_screen/business_details_private_limited_five_screen.dart';
import 'package:pra_s_application2/presentation/business_details_private_limited_five_screen/binding/business_details_private_limited_five_binding.dart';
import 'package:pra_s_application2/presentation/select_bank_one_screen/select_bank_one_screen.dart';
import 'package:pra_s_application2/presentation/select_bank_one_screen/binding/select_bank_one_binding.dart';
import 'package:pra_s_application2/presentation/notification_four_screen/notification_four_screen.dart';
import 'package:pra_s_application2/presentation/notification_four_screen/binding/notification_four_binding.dart';
import 'package:pra_s_application2/presentation/notification_two_screen/notification_two_screen.dart';
import 'package:pra_s_application2/presentation/notification_two_screen/binding/notification_two_binding.dart';
import 'package:pra_s_application2/presentation/b_guest_dashboard_disabled_coming_soon_screen/b_guest_dashboard_disabled_coming_soon_screen.dart';
import 'package:pra_s_application2/presentation/b_guest_dashboard_disabled_coming_soon_screen/binding/b_guest_dashboard_disabled_coming_soon_binding.dart';
import 'package:pra_s_application2/presentation/select_account_no_screen/select_account_no_screen.dart';
import 'package:pra_s_application2/presentation/select_account_no_screen/binding/select_account_no_binding.dart';
import 'package:pra_s_application2/presentation/guest_board_without_registration_one_screen/guest_board_without_registration_one_screen.dart';
import 'package:pra_s_application2/presentation/guest_board_without_registration_one_screen/binding/guest_board_without_registration_one_binding.dart';
import 'package:pra_s_application2/presentation/netbanking_screen/netbanking_screen.dart';
import 'package:pra_s_application2/presentation/netbanking_screen/binding/netbanking_binding.dart';
import 'package:pra_s_application2/presentation/pockets_screen/pockets_screen.dart';
import 'package:pra_s_application2/presentation/pockets_screen/binding/pockets_binding.dart';
import 'package:pra_s_application2/presentation/aadhar_screen/aadhar_screen.dart';
import 'package:pra_s_application2/presentation/aadhar_screen/binding/aadhar_binding.dart';
import 'package:pra_s_application2/presentation/switch_view_pop_up_for_users_having_screen/switch_view_pop_up_for_users_having_screen.dart';
import 'package:pra_s_application2/presentation/switch_view_pop_up_for_users_having_screen/binding/switch_view_pop_up_for_users_having_binding.dart';
import 'package:pra_s_application2/presentation/scan_qr_five_screen/scan_qr_five_screen.dart';
import 'package:pra_s_application2/presentation/scan_qr_five_screen/binding/scan_qr_five_binding.dart';
import 'package:pra_s_application2/presentation/mpin_fourteen_screen/mpin_fourteen_screen.dart';
import 'package:pra_s_application2/presentation/mpin_fourteen_screen/binding/mpin_fourteen_binding.dart';
import 'package:pra_s_application2/presentation/select_bank_screen/select_bank_screen.dart';
import 'package:pra_s_application2/presentation/select_bank_screen/binding/select_bank_binding.dart';
import 'package:pra_s_application2/presentation/business_details_individual_ten_screen/business_details_individual_ten_screen.dart';
import 'package:pra_s_application2/presentation/business_details_individual_ten_screen/binding/business_details_individual_ten_binding.dart';
import 'package:pra_s_application2/presentation/scan_qr_six_screen/scan_qr_six_screen.dart';
import 'package:pra_s_application2/presentation/scan_qr_six_screen/binding/scan_qr_six_binding.dart';
import 'package:pra_s_application2/presentation/notification_three_screen/notification_three_screen.dart';
import 'package:pra_s_application2/presentation/notification_three_screen/binding/notification_three_binding.dart';
import 'package:pra_s_application2/presentation/notification_five_screen/notification_five_screen.dart';
import 'package:pra_s_application2/presentation/notification_five_screen/binding/notification_five_binding.dart';
import 'package:pra_s_application2/presentation/ifsc_code_search_one_screen/ifsc_code_search_one_screen.dart';
import 'package:pra_s_application2/presentation/ifsc_code_search_one_screen/binding/ifsc_code_search_one_binding.dart';
import 'package:pra_s_application2/presentation/current_account_pop_us_screen/current_account_pop_us_screen.dart';
import 'package:pra_s_application2/presentation/current_account_pop_us_screen/binding/current_account_pop_us_binding.dart';
import 'package:pra_s_application2/presentation/od_pop_up_screen/od_pop_up_screen.dart';
import 'package:pra_s_application2/presentation/od_pop_up_screen/binding/od_pop_up_binding.dart';
import 'package:pra_s_application2/presentation/pos_device_pop_up_screen/pos_device_pop_up_screen.dart';
import 'package:pra_s_application2/presentation/pos_device_pop_up_screen/binding/pos_device_pop_up_binding.dart';
import 'package:pra_s_application2/presentation/complete_suit_pop_up_screen/complete_suit_pop_up_screen.dart';
import 'package:pra_s_application2/presentation/complete_suit_pop_up_screen/binding/complete_suit_pop_up_binding.dart';
import 'package:pra_s_application2/presentation/choose_sim_eight_screen/choose_sim_eight_screen.dart';
import 'package:pra_s_application2/presentation/choose_sim_eight_screen/binding/choose_sim_eight_binding.dart';
import 'package:pra_s_application2/presentation/set_upi_four_screen/set_upi_four_screen.dart';
import 'package:pra_s_application2/presentation/set_upi_four_screen/binding/set_upi_four_binding.dart';
import 'package:pra_s_application2/presentation/apply_pos_screen/apply_pos_screen.dart';
import 'package:pra_s_application2/presentation/apply_pos_screen/binding/apply_pos_binding.dart';
import 'package:pra_s_application2/presentation/all_in_one_qr_screen/all_in_one_qr_screen.dart';
import 'package:pra_s_application2/presentation/all_in_one_qr_screen/binding/all_in_one_qr_binding.dart';
import 'package:pra_s_application2/presentation/tap_on_phone_screen/tap_on_phone_screen.dart';
import 'package:pra_s_application2/presentation/tap_on_phone_screen/binding/tap_on_phone_binding.dart';
import 'package:pra_s_application2/presentation/card_with_different_cass_screen/card_with_different_cass_screen.dart';
import 'package:pra_s_application2/presentation/card_with_different_cass_screen/binding/card_with_different_cass_binding.dart';
import 'package:pra_s_application2/presentation/principle_details_chnage_address_two_screen/principle_details_chnage_address_two_screen.dart';
import 'package:pra_s_application2/presentation/principle_details_chnage_address_two_screen/binding/principle_details_chnage_address_two_binding.dart';
import 'package:pra_s_application2/presentation/aadhar_verification_screen/aadhar_verification_screen.dart';
import 'package:pra_s_application2/presentation/aadhar_verification_screen/binding/aadhar_verification_binding.dart';
import 'package:pra_s_application2/presentation/otp_screen/otp_screen.dart';
import 'package:pra_s_application2/presentation/otp_screen/binding/otp_binding.dart';
import 'package:pra_s_application2/presentation/principle_details_chnage_address_one_screen/principle_details_chnage_address_one_screen.dart';
import 'package:pra_s_application2/presentation/principle_details_chnage_address_one_screen/binding/principle_details_chnage_address_one_binding.dart';
import 'package:pra_s_application2/presentation/final_congrats_screen/final_congrats_screen.dart';
import 'package:pra_s_application2/presentation/final_congrats_screen/binding/final_congrats_binding.dart';
import 'package:pra_s_application2/presentation/error1_screen/error1_screen.dart';
import 'package:pra_s_application2/presentation/error1_screen/binding/error1_binding.dart';
import 'package:pra_s_application2/presentation/business_details_sole_proprietor_five_screen/business_details_sole_proprietor_five_screen.dart';
import 'package:pra_s_application2/presentation/business_details_sole_proprietor_five_screen/binding/business_details_sole_proprietor_five_binding.dart';
import 'package:pra_s_application2/presentation/business_details_private_limited_four_screen/business_details_private_limited_four_screen.dart';
import 'package:pra_s_application2/presentation/business_details_private_limited_four_screen/binding/business_details_private_limited_four_binding.dart';
import 'package:pra_s_application2/presentation/mpin_thirteen_screen/mpin_thirteen_screen.dart';
import 'package:pra_s_application2/presentation/mpin_thirteen_screen/binding/mpin_thirteen_binding.dart';
import 'package:pra_s_application2/presentation/mpin_fifteen_screen/mpin_fifteen_screen.dart';
import 'package:pra_s_application2/presentation/mpin_fifteen_screen/binding/mpin_fifteen_binding.dart';
import 'package:pra_s_application2/presentation/ifsc_code_search_screen/ifsc_code_search_screen.dart';
import 'package:pra_s_application2/presentation/ifsc_code_search_screen/binding/ifsc_code_search_binding.dart';
import 'package:pra_s_application2/presentation/select_bank_two_screen/select_bank_two_screen.dart';
import 'package:pra_s_application2/presentation/select_bank_two_screen/binding/select_bank_two_binding.dart';
import 'package:pra_s_application2/presentation/guest_dashboard_two_screen/guest_dashboard_two_screen.dart';
import 'package:pra_s_application2/presentation/guest_dashboard_two_screen/binding/guest_dashboard_two_binding.dart';
import 'package:pra_s_application2/presentation/business_details_individual_nine_screen/business_details_individual_nine_screen.dart';
import 'package:pra_s_application2/presentation/business_details_individual_nine_screen/binding/business_details_individual_nine_binding.dart';
import 'package:pra_s_application2/presentation/choose_sim_seven_screen/choose_sim_seven_screen.dart';
import 'package:pra_s_application2/presentation/choose_sim_seven_screen/binding/choose_sim_seven_binding.dart';
import 'package:pra_s_application2/presentation/choose_sim_six_screen/choose_sim_six_screen.dart';
import 'package:pra_s_application2/presentation/choose_sim_six_screen/binding/choose_sim_six_binding.dart';
import 'package:pra_s_application2/presentation/rewards_screen/rewards_screen.dart';
import 'package:pra_s_application2/presentation/rewards_screen/binding/rewards_binding.dart';
import 'package:pra_s_application2/presentation/with_login_using_icici_credentials_screen/with_login_using_icici_credentials_screen.dart';
import 'package:pra_s_application2/presentation/with_login_using_icici_credentials_screen/binding/with_login_using_icici_credentials_binding.dart';
import 'package:pra_s_application2/presentation/mpin_login_unchecked_screen/mpin_login_unchecked_screen.dart';
import 'package:pra_s_application2/presentation/mpin_login_unchecked_screen/binding/mpin_login_unchecked_binding.dart';
import 'package:pra_s_application2/presentation/mpin_login_unchecked_one_screen/mpin_login_unchecked_one_screen.dart';
import 'package:pra_s_application2/presentation/mpin_login_unchecked_one_screen/binding/mpin_login_unchecked_one_binding.dart';
import 'package:pra_s_application2/presentation/business_details_individual_eleven_screen/business_details_individual_eleven_screen.dart';
import 'package:pra_s_application2/presentation/business_details_individual_eleven_screen/binding/business_details_individual_eleven_binding.dart';
import 'package:pra_s_application2/presentation/mpin_eighteen_screen/mpin_eighteen_screen.dart';
import 'package:pra_s_application2/presentation/mpin_eighteen_screen/binding/mpin_eighteen_binding.dart';
import 'package:pra_s_application2/presentation/mpin_twentytwo_screen/mpin_twentytwo_screen.dart';
import 'package:pra_s_application2/presentation/mpin_twentytwo_screen/binding/mpin_twentytwo_binding.dart';
import 'package:pra_s_application2/presentation/ifsc_code_search_two_screen/ifsc_code_search_two_screen.dart';
import 'package:pra_s_application2/presentation/ifsc_code_search_two_screen/binding/ifsc_code_search_two_binding.dart';
import 'package:pra_s_application2/presentation/bank_name_auto_populated_screen/bank_name_auto_populated_screen.dart';
import 'package:pra_s_application2/presentation/bank_name_auto_populated_screen/binding/bank_name_auto_populated_binding.dart';
import 'package:pra_s_application2/presentation/enter_account_details_other_banks_one_screen/enter_account_details_other_banks_one_screen.dart';
import 'package:pra_s_application2/presentation/enter_account_details_other_banks_one_screen/binding/enter_account_details_other_banks_one_binding.dart';
import 'package:pra_s_application2/presentation/frame_1888_screen/frame_1888_screen.dart';
import 'package:pra_s_application2/presentation/frame_1888_screen/binding/frame_1888_binding.dart';
import 'package:pra_s_application2/presentation/frame_1948_screen/frame_1948_screen.dart';
import 'package:pra_s_application2/presentation/frame_1948_screen/binding/frame_1948_binding.dart';
import 'package:pra_s_application2/presentation/aadhar_verification1_screen/aadhar_verification1_screen.dart';
import 'package:pra_s_application2/presentation/aadhar_verification1_screen/binding/aadhar_verification1_binding.dart';
import 'package:pra_s_application2/presentation/aadhar_added_screen/aadhar_added_screen.dart';
import 'package:pra_s_application2/presentation/aadhar_added_screen/binding/aadhar_added_binding.dart';
import 'package:pra_s_application2/presentation/otp1_screen/otp1_screen.dart';
import 'package:pra_s_application2/presentation/otp1_screen/binding/otp1_binding.dart';
import 'package:pra_s_application2/presentation/principle_details_chnage_address_three_screen/principle_details_chnage_address_three_screen.dart';
import 'package:pra_s_application2/presentation/principle_details_chnage_address_three_screen/binding/principle_details_chnage_address_three_binding.dart';
import 'package:pra_s_application2/presentation/final_congrats_screen_one_screen/final_congrats_screen_one_screen.dart';
import 'package:pra_s_application2/presentation/final_congrats_screen_one_screen/binding/final_congrats_screen_one_binding.dart';
import 'package:pra_s_application2/presentation/error2_screen/error2_screen.dart';
import 'package:pra_s_application2/presentation/error2_screen/binding/error2_binding.dart';
import 'package:pra_s_application2/presentation/skip_pop_up_screen/skip_pop_up_screen.dart';
import 'package:pra_s_application2/presentation/skip_pop_up_screen/binding/skip_pop_up_binding.dart';
import 'package:pra_s_application2/presentation/verify_mobile_no_two_screen/verify_mobile_no_two_screen.dart';
import 'package:pra_s_application2/presentation/verify_mobile_no_two_screen/binding/verify_mobile_no_two_binding.dart';
import 'package:pra_s_application2/presentation/verifying_mobile_eleven_screen/verifying_mobile_eleven_screen.dart';
import 'package:pra_s_application2/presentation/verifying_mobile_eleven_screen/binding/verifying_mobile_eleven_binding.dart';
import 'package:pra_s_application2/presentation/verifying_mobile_eight_screen/verifying_mobile_eight_screen.dart';
import 'package:pra_s_application2/presentation/verifying_mobile_eight_screen/binding/verifying_mobile_eight_binding.dart';
import 'package:pra_s_application2/presentation/verifying_mobile_ten_screen/verifying_mobile_ten_screen.dart';
import 'package:pra_s_application2/presentation/verifying_mobile_ten_screen/binding/verifying_mobile_ten_binding.dart';
import 'package:pra_s_application2/presentation/mpin_twenty_screen/mpin_twenty_screen.dart';
import 'package:pra_s_application2/presentation/mpin_twenty_screen/binding/mpin_twenty_binding.dart';
import 'package:pra_s_application2/presentation/mpin_set_three_screen/mpin_set_three_screen.dart';
import 'package:pra_s_application2/presentation/mpin_set_three_screen/binding/mpin_set_three_binding.dart';
import 'package:pra_s_application2/presentation/guest_landing_page_three_screen/guest_landing_page_three_screen.dart';
import 'package:pra_s_application2/presentation/guest_landing_page_three_screen/binding/guest_landing_page_three_binding.dart';
import 'package:pra_s_application2/presentation/business_details_individual_fourteen_screen/business_details_individual_fourteen_screen.dart';
import 'package:pra_s_application2/presentation/business_details_individual_fourteen_screen/binding/business_details_individual_fourteen_binding.dart';
import 'package:pra_s_application2/presentation/scan_qr_seven_screen/scan_qr_seven_screen.dart';
import 'package:pra_s_application2/presentation/scan_qr_seven_screen/binding/scan_qr_seven_binding.dart';
import 'package:pra_s_application2/presentation/business_details_sole_proprietor_six_screen/business_details_sole_proprietor_six_screen.dart';
import 'package:pra_s_application2/presentation/business_details_sole_proprietor_six_screen/binding/business_details_sole_proprietor_six_binding.dart';
import 'package:pra_s_application2/presentation/business_details_private_limited_seven_screen/business_details_private_limited_seven_screen.dart';
import 'package:pra_s_application2/presentation/business_details_private_limited_seven_screen/binding/business_details_private_limited_seven_binding.dart';
import 'package:pra_s_application2/presentation/mpin_twentythree_screen/mpin_twentythree_screen.dart';
import 'package:pra_s_application2/presentation/mpin_twentythree_screen/binding/mpin_twentythree_binding.dart';
import 'package:pra_s_application2/presentation/business_details_individual_thirteen_screen/business_details_individual_thirteen_screen.dart';
import 'package:pra_s_application2/presentation/business_details_individual_thirteen_screen/binding/business_details_individual_thirteen_binding.dart';
import 'package:pra_s_application2/presentation/scan_qr_eight_screen/scan_qr_eight_screen.dart';
import 'package:pra_s_application2/presentation/scan_qr_eight_screen/binding/scan_qr_eight_binding.dart';
import 'package:pra_s_application2/presentation/mpin_seventeen_screen/mpin_seventeen_screen.dart';
import 'package:pra_s_application2/presentation/mpin_seventeen_screen/binding/mpin_seventeen_binding.dart';
import 'package:pra_s_application2/presentation/mpin_twentyone_screen/mpin_twentyone_screen.dart';
import 'package:pra_s_application2/presentation/mpin_twentyone_screen/binding/mpin_twentyone_binding.dart';
import 'package:pra_s_application2/presentation/choose_sim_ten_screen/choose_sim_ten_screen.dart';
import 'package:pra_s_application2/presentation/choose_sim_ten_screen/binding/choose_sim_ten_binding.dart';
import 'package:pra_s_application2/presentation/business_details_sole_proprietor_seven_screen/business_details_sole_proprietor_seven_screen.dart';
import 'package:pra_s_application2/presentation/business_details_sole_proprietor_seven_screen/binding/business_details_sole_proprietor_seven_binding.dart';
import 'package:pra_s_application2/presentation/business_details_private_limited_six_screen/business_details_private_limited_six_screen.dart';
import 'package:pra_s_application2/presentation/business_details_private_limited_six_screen/binding/business_details_private_limited_six_binding.dart';
import 'package:pra_s_application2/presentation/document_upload_landing_screen/document_upload_landing_screen.dart';
import 'package:pra_s_application2/presentation/document_upload_landing_screen/binding/document_upload_landing_binding.dart';
import 'package:pra_s_application2/presentation/mpin_sixteen_screen/mpin_sixteen_screen.dart';
import 'package:pra_s_application2/presentation/mpin_sixteen_screen/binding/mpin_sixteen_binding.dart';
import 'package:pra_s_application2/presentation/mpin_nineteen_screen/mpin_nineteen_screen.dart';
import 'package:pra_s_application2/presentation/mpin_nineteen_screen/binding/mpin_nineteen_binding.dart';
import 'package:pra_s_application2/presentation/business_details_individual_twelve_screen/business_details_individual_twelve_screen.dart';
import 'package:pra_s_application2/presentation/business_details_individual_twelve_screen/binding/business_details_individual_twelve_binding.dart';
import 'package:pra_s_application2/presentation/choose_sim_nine_screen/choose_sim_nine_screen.dart';
import 'package:pra_s_application2/presentation/choose_sim_nine_screen/binding/choose_sim_nine_binding.dart';
import 'package:pra_s_application2/presentation/choose_sim_eleven_screen/choose_sim_eleven_screen.dart';
import 'package:pra_s_application2/presentation/choose_sim_eleven_screen/binding/choose_sim_eleven_binding.dart';
import 'package:pra_s_application2/presentation/business_details_individual_fifteen_screen/business_details_individual_fifteen_screen.dart';
import 'package:pra_s_application2/presentation/business_details_individual_fifteen_screen/binding/business_details_individual_fifteen_binding.dart';
import 'package:pra_s_application2/presentation/error3_screen/error3_screen.dart';
import 'package:pra_s_application2/presentation/error3_screen/binding/error3_binding.dart';
import 'package:pra_s_application2/presentation/gstin_details_screen/gstin_details_screen.dart';
import 'package:pra_s_application2/presentation/gstin_details_screen/binding/gstin_details_binding.dart';
import 'package:pra_s_application2/presentation/gstin_added_screen/gstin_added_screen.dart';
import 'package:pra_s_application2/presentation/gstin_added_screen/binding/gstin_added_binding.dart';
import 'package:pra_s_application2/presentation/final_success_screen/final_success_screen.dart';
import 'package:pra_s_application2/presentation/final_success_screen/binding/final_success_binding.dart';
import 'package:pra_s_application2/presentation/personal_details_one_screen/personal_details_one_screen.dart';
import 'package:pra_s_application2/presentation/personal_details_one_screen/binding/personal_details_one_binding.dart';
import 'package:pra_s_application2/presentation/personal_details_two_screen/personal_details_two_screen.dart';
import 'package:pra_s_application2/presentation/personal_details_two_screen/binding/personal_details_two_binding.dart';
import 'package:pra_s_application2/presentation/verify_mobile_no_three_screen/verify_mobile_no_three_screen.dart';
import 'package:pra_s_application2/presentation/verify_mobile_no_three_screen/binding/verify_mobile_no_three_binding.dart';
import 'package:pra_s_application2/presentation/verifying_mobile_nine_screen/verifying_mobile_nine_screen.dart';
import 'package:pra_s_application2/presentation/verifying_mobile_nine_screen/binding/verifying_mobile_nine_binding.dart';
import 'package:pra_s_application2/presentation/verifying_mobile_seven_screen/verifying_mobile_seven_screen.dart';
import 'package:pra_s_application2/presentation/verifying_mobile_seven_screen/binding/verifying_mobile_seven_binding.dart';
import 'package:pra_s_application2/presentation/verifying_mobile_six_screen/verifying_mobile_six_screen.dart';
import 'package:pra_s_application2/presentation/verifying_mobile_six_screen/binding/verifying_mobile_six_binding.dart';
import 'package:pra_s_application2/presentation/mpin_nine_screen/mpin_nine_screen.dart';
import 'package:pra_s_application2/presentation/mpin_nine_screen/binding/mpin_nine_binding.dart';
import 'package:pra_s_application2/presentation/mpin_two_screen/mpin_two_screen.dart';
import 'package:pra_s_application2/presentation/mpin_two_screen/binding/mpin_two_binding.dart';
import 'package:pra_s_application2/presentation/mpin_one_screen/mpin_one_screen.dart';
import 'package:pra_s_application2/presentation/mpin_one_screen/binding/mpin_one_binding.dart';
import 'package:pra_s_application2/presentation/mpin_set_one_screen/mpin_set_one_screen.dart';
import 'package:pra_s_application2/presentation/mpin_set_one_screen/binding/mpin_set_one_binding.dart';
import 'package:pra_s_application2/presentation/guest_landing_page_one_screen/guest_landing_page_one_screen.dart';
import 'package:pra_s_application2/presentation/guest_landing_page_one_screen/binding/guest_landing_page_one_binding.dart';
import 'package:pra_s_application2/presentation/business_details_individual_one_screen/business_details_individual_one_screen.dart';
import 'package:pra_s_application2/presentation/business_details_individual_one_screen/binding/business_details_individual_one_binding.dart';
import 'package:pra_s_application2/presentation/scan_qr_four_screen/scan_qr_four_screen.dart';
import 'package:pra_s_application2/presentation/scan_qr_four_screen/binding/scan_qr_four_binding.dart';
import 'package:pra_s_application2/presentation/business_details_sole_proprietor_two_screen/business_details_sole_proprietor_two_screen.dart';
import 'package:pra_s_application2/presentation/business_details_sole_proprietor_two_screen/binding/business_details_sole_proprietor_two_binding.dart';
import 'package:pra_s_application2/presentation/business_details_private_limited_one_screen/business_details_private_limited_one_screen.dart';
import 'package:pra_s_application2/presentation/business_details_private_limited_one_screen/binding/business_details_private_limited_one_binding.dart';
import 'package:pra_s_application2/presentation/gstin_details_missing_screen/gstin_details_missing_screen.dart';
import 'package:pra_s_application2/presentation/gstin_details_missing_screen/binding/gstin_details_missing_binding.dart';
import 'package:pra_s_application2/presentation/mpin_five_screen/mpin_five_screen.dart';
import 'package:pra_s_application2/presentation/mpin_five_screen/binding/mpin_five_binding.dart';
import 'package:pra_s_application2/presentation/mpin_six_screen/mpin_six_screen.dart';
import 'package:pra_s_application2/presentation/mpin_six_screen/binding/mpin_six_binding.dart';
import 'package:pra_s_application2/presentation/mpin_ten_screen/mpin_ten_screen.dart';
import 'package:pra_s_application2/presentation/mpin_ten_screen/binding/mpin_ten_binding.dart';
import 'package:pra_s_application2/presentation/business_details_individual_four_screen/business_details_individual_four_screen.dart';
import 'package:pra_s_application2/presentation/business_details_individual_four_screen/binding/business_details_individual_four_binding.dart';
import 'package:pra_s_application2/presentation/scan_qr_one_screen/scan_qr_one_screen.dart';
import 'package:pra_s_application2/presentation/scan_qr_one_screen/binding/scan_qr_one_binding.dart';
import 'package:pra_s_application2/presentation/choose_sim_three_screen/choose_sim_three_screen.dart';
import 'package:pra_s_application2/presentation/choose_sim_three_screen/binding/choose_sim_three_binding.dart';
import 'package:pra_s_application2/presentation/business_details_sole_proprietor_four_screen/business_details_sole_proprietor_four_screen.dart';
import 'package:pra_s_application2/presentation/business_details_sole_proprietor_four_screen/binding/business_details_sole_proprietor_four_binding.dart';
import 'package:pra_s_application2/presentation/business_details_private_limited_two_screen/business_details_private_limited_two_screen.dart';
import 'package:pra_s_application2/presentation/business_details_private_limited_two_screen/binding/business_details_private_limited_two_binding.dart';
import 'package:pra_s_application2/presentation/business_details_individual_five_screen/business_details_individual_five_screen.dart';
import 'package:pra_s_application2/presentation/business_details_individual_five_screen/binding/business_details_individual_five_binding.dart';
import 'package:pra_s_application2/presentation/choose_sim_two_screen/choose_sim_two_screen.dart';
import 'package:pra_s_application2/presentation/choose_sim_two_screen/binding/choose_sim_two_binding.dart';
import 'package:pra_s_application2/presentation/choose_sim_five_screen/choose_sim_five_screen.dart';
import 'package:pra_s_application2/presentation/choose_sim_five_screen/binding/choose_sim_five_binding.dart';
import 'package:pra_s_application2/presentation/business_details_individual_seven_screen/business_details_individual_seven_screen.dart';
import 'package:pra_s_application2/presentation/business_details_individual_seven_screen/binding/business_details_individual_seven_binding.dart';
import 'package:pra_s_application2/presentation/verify_mobile_no_one_screen/verify_mobile_no_one_screen.dart';
import 'package:pra_s_application2/presentation/verify_mobile_no_one_screen/binding/verify_mobile_no_one_binding.dart';
import 'package:pra_s_application2/presentation/verifying_mobile_three_screen/verifying_mobile_three_screen.dart';
import 'package:pra_s_application2/presentation/verifying_mobile_three_screen/binding/verifying_mobile_three_binding.dart';
import 'package:pra_s_application2/presentation/verifying_mobile_four_screen/verifying_mobile_four_screen.dart';
import 'package:pra_s_application2/presentation/verifying_mobile_four_screen/binding/verifying_mobile_four_binding.dart';
import 'package:pra_s_application2/presentation/verifying_mobile_five_screen/verifying_mobile_five_screen.dart';
import 'package:pra_s_application2/presentation/verifying_mobile_five_screen/binding/verifying_mobile_five_binding.dart';
import 'package:pra_s_application2/presentation/mpin_eight_screen/mpin_eight_screen.dart';
import 'package:pra_s_application2/presentation/mpin_eight_screen/binding/mpin_eight_binding.dart';
import 'package:pra_s_application2/presentation/mpin_four_screen/mpin_four_screen.dart';
import 'package:pra_s_application2/presentation/mpin_four_screen/binding/mpin_four_binding.dart';
import 'package:pra_s_application2/presentation/mpin_seven_screen/mpin_seven_screen.dart';
import 'package:pra_s_application2/presentation/mpin_seven_screen/binding/mpin_seven_binding.dart';
import 'package:pra_s_application2/presentation/mpin_set_two_screen/mpin_set_two_screen.dart';
import 'package:pra_s_application2/presentation/mpin_set_two_screen/binding/mpin_set_two_binding.dart';
import 'package:pra_s_application2/presentation/guest_landing_page_two_screen/guest_landing_page_two_screen.dart';
import 'package:pra_s_application2/presentation/guest_landing_page_two_screen/binding/guest_landing_page_two_binding.dart';
import 'package:pra_s_application2/presentation/business_details_individual_three_screen/business_details_individual_three_screen.dart';
import 'package:pra_s_application2/presentation/business_details_individual_three_screen/binding/business_details_individual_three_binding.dart';
import 'package:pra_s_application2/presentation/scan_qr_two_screen/scan_qr_two_screen.dart';
import 'package:pra_s_application2/presentation/scan_qr_two_screen/binding/scan_qr_two_binding.dart';
import 'package:pra_s_application2/presentation/business_details_sole_proprietor_three_screen/business_details_sole_proprietor_three_screen.dart';
import 'package:pra_s_application2/presentation/business_details_sole_proprietor_three_screen/binding/business_details_sole_proprietor_three_binding.dart';
import 'package:pra_s_application2/presentation/business_details_private_limited_screen/business_details_private_limited_screen.dart';
import 'package:pra_s_application2/presentation/business_details_private_limited_screen/binding/business_details_private_limited_binding.dart';
import 'package:pra_s_application2/presentation/mpin_eleven_screen/mpin_eleven_screen.dart';
import 'package:pra_s_application2/presentation/mpin_eleven_screen/binding/mpin_eleven_binding.dart';
import 'package:pra_s_application2/presentation/mpin_twelve_screen/mpin_twelve_screen.dart';
import 'package:pra_s_application2/presentation/mpin_twelve_screen/binding/mpin_twelve_binding.dart';
import 'package:pra_s_application2/presentation/mpin_three_screen/mpin_three_screen.dart';
import 'package:pra_s_application2/presentation/mpin_three_screen/binding/mpin_three_binding.dart';
import 'package:pra_s_application2/presentation/business_details_individual_six_screen/business_details_individual_six_screen.dart';
import 'package:pra_s_application2/presentation/business_details_individual_six_screen/binding/business_details_individual_six_binding.dart';
import 'package:pra_s_application2/presentation/scan_qr_three_screen/scan_qr_three_screen.dart';
import 'package:pra_s_application2/presentation/scan_qr_three_screen/binding/scan_qr_three_binding.dart';
import 'package:pra_s_application2/presentation/choose_sim_one_screen/choose_sim_one_screen.dart';
import 'package:pra_s_application2/presentation/choose_sim_one_screen/binding/choose_sim_one_binding.dart';
import 'package:pra_s_application2/presentation/business_details_sole_proprietor_one_screen/business_details_sole_proprietor_one_screen.dart';
import 'package:pra_s_application2/presentation/business_details_sole_proprietor_one_screen/binding/business_details_sole_proprietor_one_binding.dart';
import 'package:pra_s_application2/presentation/business_details_private_limited_three_screen/business_details_private_limited_three_screen.dart';
import 'package:pra_s_application2/presentation/business_details_private_limited_three_screen/binding/business_details_private_limited_three_binding.dart';
import 'package:pra_s_application2/presentation/business_details_individual_eight_screen/business_details_individual_eight_screen.dart';
import 'package:pra_s_application2/presentation/business_details_individual_eight_screen/binding/business_details_individual_eight_binding.dart';
import 'package:pra_s_application2/presentation/choose_sim_four_screen/choose_sim_four_screen.dart';
import 'package:pra_s_application2/presentation/choose_sim_four_screen/binding/choose_sim_four_binding.dart';
import 'package:pra_s_application2/presentation/choose_sim_screen/choose_sim_screen.dart';
import 'package:pra_s_application2/presentation/choose_sim_screen/binding/choose_sim_binding.dart';
import 'package:pra_s_application2/presentation/business_details_individual_two_screen/business_details_individual_two_screen.dart';
import 'package:pra_s_application2/presentation/business_details_individual_two_screen/binding/business_details_individual_two_binding.dart';
import 'package:pra_s_application2/presentation/app_navigation_screen/app_navigation_screen.dart';
import 'package:pra_s_application2/presentation/app_navigation_screen/binding/app_navigation_binding.dart';
import 'package:get/get.dart';

class AppRoutes {
  static const String androidSmallThreeScreen = '/android_small_three_screen';

  static const String guestBoardWithoutRegistrationScreen =
      '/guest_board_without_registration_screen';

  static const String notificationScreen = '/notification_screen';

  static const String guestMerchantDashboardWithUpgradeBannerScreen =
      '/guest_merchant_dashboard_with_upgrade_banner_screen';

  static const String guestMerchantDashboardWithLiveServicesOneScreen =
      '/guest_merchant_dashboard_with_live_services_one_screen';

  static const String guestMerchantDashboardWithUpgradeBannerOnePage =
      '/guest_merchant_dashboard_with_upgrade_banner_one_page';

  static const String
      guestMerchantDashboardWithUpgradeBannerOneContainerScreen =
      '/guest_merchant_dashboard_with_upgrade_banner_one_container_screen';

  static const String guestMerchantDashboardWithLiveServicesScreen =
      '/guest_merchant_dashboard_with_live_services_screen';

  static const String guestDashboardOneScreen = '/guest_dashboard_one_screen';

  static const String guestDashboardScreen = '/guest_dashboard_screen';

  static const String notificationOneScreen = '/notification_one_screen';

  static const String guestProfile2AccountsScreen =
      '/guest_profile_2_accounts_screen';

  static const String loanServicesScreen = '/loan_services_screen';

  static const String myBusinessCardScreen = '/my_business_card_screen';

  static const String myBusinessCardEditScreen =
      '/my_business_card_edit_screen';

  static const String myBusinessCardSavedChangesScreen =
      '/my_business_card_saved_changes_screen';

  static const String myBusinessCardBackgroundScreen =
      '/my_business_card_background_screen';

  static const String principleDetailsChnageAddressScreen =
      '/principle_details_chnage_address_screen';

  static const String addharDetailsAddedScreen = '/addhar_details_added_screen';

  static const String errorScreen = '/error_screen';

  static const String productSelectionScreen = '/product_selection_screen';

  static const String currentACProductSelectedScreen =
      '/current_a_c_product_selected_screen';

  static const String odProductSelectedScreen = '/od_product_selected_screen';

  static const String posDeviceProductSelectedScreen =
      '/pos_device_product_selected_screen';

  static const String completeSuitProductSelectedScreen =
      '/complete_suit_product_selected_screen';

  static const String k25Screen = '/k25_screen';

  static const String setUpiOneScreen = '/set_upi_one_screen';

  static const String setUpiValidScreen = '/set_upi_valid_screen';

  static const String setUpiInvalidScreen = '/set_upi_invalid_screen';

  static const String setUpiTwoScreen = '/set_upi_two_screen';

  static const String scanQrCodeScreen = '/scan_qr_code_screen';

  static const String setUpiThreeScreen = '/set_upi_three_screen';

  static const String upiDetailsAddedScreen = '/upi_details_added_screen';

  static const String enterAccountDetailsOtherBanksScreen =
      '/enter_account_details_other_banks_screen';

  static const String accountDetailsAddedOtherBanksScreen =
      '/account_details_added_other_banks_screen';

  static const String verifyMobileNoScreen = '/verify_mobile_no_screen';

  static const String verifyingMobileOneScreen = '/verifying_mobile_one_screen';

  static const String verifyingMobileScreen = '/verifying_mobile_screen';

  static const String verifyingMobileTwoScreen = '/verifying_mobile_two_screen';

  static const String mpinScreen = '/mpin_screen';

  static const String mpinSetScreen = '/mpin_set_screen';

  static const String selectAccountTypeScreen = '/select_account_type_screen';

  static const String accountVerifingOneScreen = '/account_verifing_one_screen';

  static const String accountVerifingScreen = '/account_verifing_screen';

  static const String accountVerifiedScreen = '/account_verified_screen';

  static const String accountFoundScreen = '/account_found_screen';

  static const String accountDetailsAddedScreen =
      '/account_details_added_screen';

  static const String guestLandingPageScreen = '/guest_landing_page_screen';

  static const String businessDetailsIndividualScreen =
      '/business_details_individual_screen';

  static const String scanQrScreen = '/scan_qr_screen';

  static const String businessDetailsSoleProprietorScreen =
      '/business_details_sole_proprietor_screen';

  static const String businessDetailsPrivateLimitedFiveScreen =
      '/business_details_private_limited_five_screen';

  static const String selectBankOneScreen = '/select_bank_one_screen';

  static const String notificationFourScreen = '/notification_four_screen';

  static const String notificationTwoScreen = '/notification_two_screen';

  static const String bGuestDashboardDisabledComingSoonScreen =
      '/b_guest_dashboard_disabled_coming_soon_screen';

  static const String selectAccountNoScreen = '/select_account_no_screen';

  static const String guestBoardWithoutRegistrationOneScreen =
      '/guest_board_without_registration_one_screen';

  static const String netbankingScreen = '/netbanking_screen';

  static const String pocketsScreen = '/pockets_screen';

  static const String aadharScreen = '/aadhar_screen';

  static const String switchViewPopUpForUsersHavingScreen =
      '/switch_view_pop_up_for_users_having_screen';

  static const String scanQrFiveScreen = '/scan_qr_five_screen';

  static const String mpinFourteenScreen = '/mpin_fourteen_screen';

  static const String selectBankScreen = '/select_bank_screen';

  static const String businessDetailsIndividualTenScreen =
      '/business_details_individual_ten_screen';

  static const String scanQrSixScreen = '/scan_qr_six_screen';

  static const String notificationThreeScreen = '/notification_three_screen';

  static const String notificationFiveScreen = '/notification_five_screen';

  static const String ifscCodeSearchOneScreen = '/ifsc_code_search_one_screen';

  static const String currentAccountPopUsScreen =
      '/current_account_pop_us_screen';

  static const String odPopUpScreen = '/od_pop_up_screen';

  static const String posDevicePopUpScreen = '/pos_device_pop_up_screen';

  static const String completeSuitPopUpScreen = '/complete_suit_pop_up_screen';

  static const String chooseSimEightScreen = '/choose_sim_eight_screen';

  static const String setUpiFourScreen = '/set_upi_four_screen';

  static const String applyPosScreen = '/apply_pos_screen';

  static const String allInOneQrScreen = '/all_in_one_qr_screen';

  static const String tapOnPhoneScreen = '/tap_on_phone_screen';

  static const String cardWithDifferentCassScreen =
      '/card_with_different_cass_screen';

  static const String principleDetailsChnageAddressTwoScreen =
      '/principle_details_chnage_address_two_screen';

  static const String aadharVerificationScreen = '/aadhar_verification_screen';

  static const String otpScreen = '/otp_screen';

  static const String principleDetailsChnageAddressOneScreen =
      '/principle_details_chnage_address_one_screen';

  static const String finalCongratsScreen = '/final_congrats_screen';

  static const String error1Screen = '/error1_screen';

  static const String businessDetailsSoleProprietorFiveScreen =
      '/business_details_sole_proprietor_five_screen';

  static const String businessDetailsPrivateLimitedFourScreen =
      '/business_details_private_limited_four_screen';

  static const String mpinThirteenScreen = '/mpin_thirteen_screen';

  static const String mpinFifteenScreen = '/mpin_fifteen_screen';

  static const String ifscCodeSearchScreen = '/ifsc_code_search_screen';

  static const String selectBankTwoScreen = '/select_bank_two_screen';

  static const String guestDashboardTwoScreen = '/guest_dashboard_two_screen';

  static const String businessDetailsIndividualNineScreen =
      '/business_details_individual_nine_screen';

  static const String chooseSimSevenScreen = '/choose_sim_seven_screen';

  static const String chooseSimSixScreen = '/choose_sim_six_screen';

  static const String rewardsScreen = '/rewards_screen';

  static const String withLoginUsingIciciCredentialsScreen =
      '/with_login_using_icici_credentials_screen';

  static const String mpinLoginUncheckedScreen = '/mpin_login_unchecked_screen';

  static const String mpinLoginUncheckedOneScreen =
      '/mpin_login_unchecked_one_screen';

  static const String businessDetailsIndividualElevenScreen =
      '/business_details_individual_eleven_screen';

  static const String mpinEighteenScreen = '/mpin_eighteen_screen';

  static const String mpinTwentytwoScreen = '/mpin_twentytwo_screen';

  static const String ifscCodeSearchTwoScreen = '/ifsc_code_search_two_screen';

  static const String bankNameAutoPopulatedScreen =
      '/bank_name_auto_populated_screen';

  static const String enterAccountDetailsOtherBanksOneScreen =
      '/enter_account_details_other_banks_one_screen';

  static const String frame1888Screen = '/frame_1888_screen';

  static const String frame1948Screen = '/frame_1948_screen';

  static const String aadharVerification1Screen =
      '/aadhar_verification1_screen';

  static const String aadharAddedScreen = '/aadhar_added_screen';

  static const String otp1Screen = '/otp1_screen';

  static const String principleDetailsChnageAddressThreeScreen =
      '/principle_details_chnage_address_three_screen';

  static const String finalCongratsScreenOneScreen =
      '/final_congrats_screen_one_screen';

  static const String error2Screen = '/error2_screen';

  static const String skipPopUpScreen = '/skip_pop_up_screen';

  static const String verifyMobileNoTwoScreen = '/verify_mobile_no_two_screen';

  static const String verifyingMobileElevenScreen =
      '/verifying_mobile_eleven_screen';

  static const String verifyingMobileEightScreen =
      '/verifying_mobile_eight_screen';

  static const String verifyingMobileTenScreen = '/verifying_mobile_ten_screen';

  static const String mpinTwentyScreen = '/mpin_twenty_screen';

  static const String mpinSetThreeScreen = '/mpin_set_three_screen';

  static const String guestLandingPageThreeScreen =
      '/guest_landing_page_three_screen';

  static const String businessDetailsIndividualFourteenScreen =
      '/business_details_individual_fourteen_screen';

  static const String scanQrSevenScreen = '/scan_qr_seven_screen';

  static const String businessDetailsSoleProprietorSixScreen =
      '/business_details_sole_proprietor_six_screen';

  static const String businessDetailsPrivateLimitedSevenScreen =
      '/business_details_private_limited_seven_screen';

  static const String mpinTwentythreeScreen = '/mpin_twentythree_screen';

  static const String businessDetailsIndividualThirteenScreen =
      '/business_details_individual_thirteen_screen';

  static const String scanQrEightScreen = '/scan_qr_eight_screen';

  static const String mpinSeventeenScreen = '/mpin_seventeen_screen';

  static const String mpinTwentyoneScreen = '/mpin_twentyone_screen';

  static const String chooseSimTenScreen = '/choose_sim_ten_screen';

  static const String businessDetailsSoleProprietorSevenScreen =
      '/business_details_sole_proprietor_seven_screen';

  static const String businessDetailsPrivateLimitedSixScreen =
      '/business_details_private_limited_six_screen';

  static const String documentUploadLandingScreen =
      '/document_upload_landing_screen';

  static const String mpinSixteenScreen = '/mpin_sixteen_screen';

  static const String mpinNineteenScreen = '/mpin_nineteen_screen';

  static const String businessDetailsIndividualTwelveScreen =
      '/business_details_individual_twelve_screen';

  static const String chooseSimNineScreen = '/choose_sim_nine_screen';

  static const String chooseSimElevenScreen = '/choose_sim_eleven_screen';

  static const String businessDetailsIndividualFifteenScreen =
      '/business_details_individual_fifteen_screen';

  static const String error3Screen = '/error3_screen';

  static const String gstinDetailsScreen = '/gstin_details_screen';

  static const String gstinAddedScreen = '/gstin_added_screen';

  static const String finalSuccessScreen = '/final_success_screen';

  static const String personalDetailsOneScreen = '/personal_details_one_screen';

  static const String personalDetailsTwoScreen = '/personal_details_two_screen';

  static const String verifyMobileNoThreeScreen =
      '/verify_mobile_no_three_screen';

  static const String verifyingMobileNineScreen =
      '/verifying_mobile_nine_screen';

  static const String verifyingMobileSevenScreen =
      '/verifying_mobile_seven_screen';

  static const String verifyingMobileSixScreen = '/verifying_mobile_six_screen';

  static const String mpinNineScreen = '/mpin_nine_screen';

  static const String mpinTwoScreen = '/mpin_two_screen';

  static const String mpinOneScreen = '/mpin_one_screen';

  static const String mpinSetOneScreen = '/mpin_set_one_screen';

  static const String guestLandingPageOneScreen =
      '/guest_landing_page_one_screen';

  static const String businessDetailsIndividualOneScreen =
      '/business_details_individual_one_screen';

  static const String scanQrFourScreen = '/scan_qr_four_screen';

  static const String businessDetailsSoleProprietorTwoScreen =
      '/business_details_sole_proprietor_two_screen';

  static const String businessDetailsPrivateLimitedOneScreen =
      '/business_details_private_limited_one_screen';

  static const String gstinDetailsMissingScreen =
      '/gstin_details_missing_screen';

  static const String mpinFiveScreen = '/mpin_five_screen';

  static const String mpinSixScreen = '/mpin_six_screen';

  static const String mpinTenScreen = '/mpin_ten_screen';

  static const String businessDetailsIndividualFourScreen =
      '/business_details_individual_four_screen';

  static const String scanQrOneScreen = '/scan_qr_one_screen';

  static const String chooseSimThreeScreen = '/choose_sim_three_screen';

  static const String businessDetailsSoleProprietorFourScreen =
      '/business_details_sole_proprietor_four_screen';

  static const String businessDetailsPrivateLimitedTwoScreen =
      '/business_details_private_limited_two_screen';

  static const String businessDetailsIndividualFiveScreen =
      '/business_details_individual_five_screen';

  static const String chooseSimTwoScreen = '/choose_sim_two_screen';

  static const String chooseSimFiveScreen = '/choose_sim_five_screen';

  static const String businessDetailsIndividualSevenScreen =
      '/business_details_individual_seven_screen';

  static const String verifyMobileNoOneScreen = '/verify_mobile_no_one_screen';

  static const String verifyingMobileThreeScreen =
      '/verifying_mobile_three_screen';

  static const String verifyingMobileFourScreen =
      '/verifying_mobile_four_screen';

  static const String verifyingMobileFiveScreen =
      '/verifying_mobile_five_screen';

  static const String mpinEightScreen = '/mpin_eight_screen';

  static const String mpinFourScreen = '/mpin_four_screen';

  static const String mpinSevenScreen = '/mpin_seven_screen';

  static const String mpinSetTwoScreen = '/mpin_set_two_screen';

  static const String guestLandingPageTwoScreen =
      '/guest_landing_page_two_screen';

  static const String businessDetailsIndividualThreeScreen =
      '/business_details_individual_three_screen';

  static const String scanQrTwoScreen = '/scan_qr_two_screen';

  static const String businessDetailsSoleProprietorThreeScreen =
      '/business_details_sole_proprietor_three_screen';

  static const String businessDetailsPrivateLimitedScreen =
      '/business_details_private_limited_screen';

  static const String mpinElevenScreen = '/mpin_eleven_screen';

  static const String mpinTwelveScreen = '/mpin_twelve_screen';

  static const String mpinThreeScreen = '/mpin_three_screen';

  static const String businessDetailsIndividualSixScreen =
      '/business_details_individual_six_screen';

  static const String scanQrThreeScreen = '/scan_qr_three_screen';

  static const String chooseSimOneScreen = '/choose_sim_one_screen';

  static const String businessDetailsSoleProprietorOneScreen =
      '/business_details_sole_proprietor_one_screen';

  static const String businessDetailsPrivateLimitedThreeScreen =
      '/business_details_private_limited_three_screen';

  static const String businessDetailsIndividualEightScreen =
      '/business_details_individual_eight_screen';

  static const String chooseSimFourScreen = '/choose_sim_four_screen';

  static const String chooseSimScreen = '/choose_sim_screen';

  static const String businessDetailsIndividualTwoScreen =
      '/business_details_individual_two_screen';

  static const String appNavigationScreen = '/app_navigation_screen';

  static String initialRoute = '/initialRoute';

  static List<GetPage> pages = [
    GetPage(
      name: androidSmallThreeScreen,
      page: () => AndroidSmallThreeScreen(),
      bindings: [
        AndroidSmallThreeBinding(),
      ],
    ),
    GetPage(
      name: guestBoardWithoutRegistrationScreen,
      page: () => GuestBoardWithoutRegistrationScreen(),
      bindings: [
        GuestBoardWithoutRegistrationBinding(),
      ],
    ),
    GetPage(
      name: notificationScreen,
      page: () => NotificationScreen(),
      bindings: [
        NotificationBinding(),
      ],
    ),
    GetPage(
      name: guestMerchantDashboardWithUpgradeBannerScreen,
      page: () => GuestMerchantDashboardWithUpgradeBannerScreen(),
      bindings: [
        GuestMerchantDashboardWithUpgradeBannerBinding(),
      ],
    ),
    GetPage(
      name: guestMerchantDashboardWithLiveServicesOneScreen,
      page: () => GuestMerchantDashboardWithLiveServicesOneScreen(),
      bindings: [
        GuestMerchantDashboardWithLiveServicesOneBinding(),
      ],
    ),
    GetPage(
      name: guestMerchantDashboardWithUpgradeBannerOneContainerScreen,
      page: () => GuestMerchantDashboardWithUpgradeBannerOneContainerScreen(),
      bindings: [
        GuestMerchantDashboardWithUpgradeBannerOneContainerBinding(),
      ],
    ),
    GetPage(
      name: guestMerchantDashboardWithLiveServicesScreen,
      page: () => GuestMerchantDashboardWithLiveServicesScreen(),
      bindings: [
        GuestMerchantDashboardWithLiveServicesBinding(),
      ],
    ),
    GetPage(
      name: guestDashboardOneScreen,
      page: () => GuestDashboardOneScreen(),
      bindings: [
        GuestDashboardOneBinding(),
      ],
    ),
    GetPage(
      name: guestDashboardScreen,
      page: () => GuestDashboardScreen(),
      bindings: [
        GuestDashboardBinding(),
      ],
    ),
    GetPage(
      name: notificationOneScreen,
      page: () => NotificationOneScreen(),
      bindings: [
        NotificationOneBinding(),
      ],
    ),
    GetPage(
      name: guestProfile2AccountsScreen,
      page: () => GuestProfile2AccountsScreen(),
      bindings: [
        GuestProfile2AccountsBinding(),
      ],
    ),
    GetPage(
      name: loanServicesScreen,
      page: () => LoanServicesScreen(),
      bindings: [
        LoanServicesBinding(),
      ],
    ),
    GetPage(
      name: myBusinessCardScreen,
      page: () => MyBusinessCardScreen(),
      bindings: [
        MyBusinessCardBinding(),
      ],
    ),
    GetPage(
      name: myBusinessCardEditScreen,
      page: () => MyBusinessCardEditScreen(),
      bindings: [
        MyBusinessCardEditBinding(),
      ],
    ),
    GetPage(
      name: myBusinessCardSavedChangesScreen,
      page: () => MyBusinessCardSavedChangesScreen(),
      bindings: [
        MyBusinessCardSavedChangesBinding(),
      ],
    ),
    GetPage(
      name: myBusinessCardBackgroundScreen,
      page: () => MyBusinessCardBackgroundScreen(),
      bindings: [
        MyBusinessCardBackgroundBinding(),
      ],
    ),
    GetPage(
      name: principleDetailsChnageAddressScreen,
      page: () => PrincipleDetailsChnageAddressScreen(),
      bindings: [
        PrincipleDetailsChnageAddressBinding(),
      ],
    ),
    GetPage(
      name: addharDetailsAddedScreen,
      page: () => AddharDetailsAddedScreen(),
      bindings: [
        AddharDetailsAddedBinding(),
      ],
    ),
    GetPage(
      name: errorScreen,
      page: () => ErrorScreen(),
      bindings: [
        ErrorBinding(),
      ],
    ),
    GetPage(
      name: productSelectionScreen,
      page: () => ProductSelectionScreen(),
      bindings: [
        ProductSelectionBinding(),
      ],
    ),
    GetPage(
      name: currentACProductSelectedScreen,
      page: () => CurrentACProductSelectedScreen(),
      bindings: [
        CurrentACProductSelectedBinding(),
      ],
    ),
    GetPage(
      name: odProductSelectedScreen,
      page: () => OdProductSelectedScreen(),
      bindings: [
        OdProductSelectedBinding(),
      ],
    ),
    GetPage(
      name: posDeviceProductSelectedScreen,
      page: () => PosDeviceProductSelectedScreen(),
      bindings: [
        PosDeviceProductSelectedBinding(),
      ],
    ),
    GetPage(
      name: completeSuitProductSelectedScreen,
      page: () => CompleteSuitProductSelectedScreen(),
      bindings: [
        CompleteSuitProductSelectedBinding(),
      ],
    ),
    GetPage(
      name: k25Screen,
      page: () => K25Screen(),
      bindings: [
        K25Binding(),
      ],
    ),
    GetPage(
      name: setUpiOneScreen,
      page: () => SetUpiOneScreen(),
      bindings: [
        SetUpiOneBinding(),
      ],
    ),
    GetPage(
      name: setUpiValidScreen,
      page: () => SetUpiValidScreen(),
      bindings: [
        SetUpiValidBinding(),
      ],
    ),
    GetPage(
      name: setUpiInvalidScreen,
      page: () => SetUpiInvalidScreen(),
      bindings: [
        SetUpiInvalidBinding(),
      ],
    ),
    GetPage(
      name: setUpiTwoScreen,
      page: () => SetUpiTwoScreen(),
      bindings: [
        SetUpiTwoBinding(),
      ],
    ),
    GetPage(
      name: scanQrCodeScreen,
      page: () => ScanQrCodeScreen(),
      bindings: [
        ScanQrCodeBinding(),
      ],
    ),
    GetPage(
      name: setUpiThreeScreen,
      page: () => SetUpiThreeScreen(),
      bindings: [
        SetUpiThreeBinding(),
      ],
    ),
    GetPage(
      name: upiDetailsAddedScreen,
      page: () => UpiDetailsAddedScreen(),
      bindings: [
        UpiDetailsAddedBinding(),
      ],
    ),
    GetPage(
      name: enterAccountDetailsOtherBanksScreen,
      page: () => EnterAccountDetailsOtherBanksScreen(),
      bindings: [
        EnterAccountDetailsOtherBanksBinding(),
      ],
    ),
    GetPage(
      name: accountDetailsAddedOtherBanksScreen,
      page: () => AccountDetailsAddedOtherBanksScreen(),
      bindings: [
        AccountDetailsAddedOtherBanksBinding(),
      ],
    ),
    GetPage(
      name: verifyMobileNoScreen,
      page: () => VerifyMobileNoScreen(),
      bindings: [
        VerifyMobileNoBinding(),
      ],
    ),
    GetPage(
      name: verifyingMobileOneScreen,
      page: () => VerifyingMobileOneScreen(),
      bindings: [
        VerifyingMobileOneBinding(),
      ],
    ),
    GetPage(
      name: verifyingMobileScreen,
      page: () => VerifyingMobileScreen(),
      bindings: [
        VerifyingMobileBinding(),
      ],
    ),
    GetPage(
      name: verifyingMobileTwoScreen,
      page: () => VerifyingMobileTwoScreen(),
      bindings: [
        VerifyingMobileTwoBinding(),
      ],
    ),
    GetPage(
      name: mpinScreen,
      page: () => MpinScreen(),
      bindings: [
        MpinBinding(),
      ],
    ),
    GetPage(
      name: mpinSetScreen,
      page: () => MpinSetScreen(),
      bindings: [
        MpinSetBinding(),
      ],
    ),
    GetPage(
      name: selectAccountTypeScreen,
      page: () => SelectAccountTypeScreen(),
      bindings: [
        SelectAccountTypeBinding(),
      ],
    ),
    GetPage(
      name: accountVerifingOneScreen,
      page: () => AccountVerifingOneScreen(),
      bindings: [
        AccountVerifingOneBinding(),
      ],
    ),
    GetPage(
      name: accountVerifingScreen,
      page: () => AccountVerifingScreen(),
      bindings: [
        AccountVerifingBinding(),
      ],
    ),
    GetPage(
      name: accountVerifiedScreen,
      page: () => AccountVerifiedScreen(),
      bindings: [
        AccountVerifiedBinding(),
      ],
    ),
    GetPage(
      name: accountFoundScreen,
      page: () => AccountFoundScreen(),
      bindings: [
        AccountFoundBinding(),
      ],
    ),
    GetPage(
      name: accountDetailsAddedScreen,
      page: () => AccountDetailsAddedScreen(),
      bindings: [
        AccountDetailsAddedBinding(),
      ],
    ),
    GetPage(
      name: guestLandingPageScreen,
      page: () => GuestLandingPageScreen(),
      bindings: [
        GuestLandingPageBinding(),
      ],
    ),
    GetPage(
      name: businessDetailsIndividualScreen,
      page: () => BusinessDetailsIndividualScreen(),
      bindings: [
        BusinessDetailsIndividualBinding(),
      ],
    ),
    GetPage(
      name: scanQrScreen,
      page: () => ScanQrScreen(),
      bindings: [
        ScanQrBinding(),
      ],
    ),
    GetPage(
      name: businessDetailsSoleProprietorScreen,
      page: () => BusinessDetailsSoleProprietorScreen(),
      bindings: [
        BusinessDetailsSoleProprietorBinding(),
      ],
    ),
    GetPage(
      name: businessDetailsPrivateLimitedFiveScreen,
      page: () => BusinessDetailsPrivateLimitedFiveScreen(),
      bindings: [
        BusinessDetailsPrivateLimitedFiveBinding(),
      ],
    ),
    GetPage(
      name: selectBankOneScreen,
      page: () => SelectBankOneScreen(),
      bindings: [
        SelectBankOneBinding(),
      ],
    ),
    GetPage(
      name: notificationFourScreen,
      page: () => NotificationFourScreen(),
      bindings: [
        NotificationFourBinding(),
      ],
    ),
    GetPage(
      name: notificationTwoScreen,
      page: () => NotificationTwoScreen(),
      bindings: [
        NotificationTwoBinding(),
      ],
    ),
    GetPage(
      name: bGuestDashboardDisabledComingSoonScreen,
      page: () => BGuestDashboardDisabledComingSoonScreen(),
      bindings: [
        BGuestDashboardDisabledComingSoonBinding(),
      ],
    ),
    GetPage(
      name: selectAccountNoScreen,
      page: () => SelectAccountNoScreen(),
      bindings: [
        SelectAccountNoBinding(),
      ],
    ),
    GetPage(
      name: guestBoardWithoutRegistrationOneScreen,
      page: () => GuestBoardWithoutRegistrationOneScreen(),
      bindings: [
        GuestBoardWithoutRegistrationOneBinding(),
      ],
    ),
    GetPage(
      name: netbankingScreen,
      page: () => NetbankingScreen(),
      bindings: [
        NetbankingBinding(),
      ],
    ),
    GetPage(
      name: pocketsScreen,
      page: () => PocketsScreen(),
      bindings: [
        PocketsBinding(),
      ],
    ),
    GetPage(
      name: aadharScreen,
      page: () => AadharScreen(),
      bindings: [
        AadharBinding(),
      ],
    ),
    GetPage(
      name: switchViewPopUpForUsersHavingScreen,
      page: () => SwitchViewPopUpForUsersHavingScreen(),
      bindings: [
        SwitchViewPopUpForUsersHavingBinding(),
      ],
    ),
    GetPage(
      name: scanQrFiveScreen,
      page: () => ScanQrFiveScreen(),
      bindings: [
        ScanQrFiveBinding(),
      ],
    ),
    GetPage(
      name: mpinFourteenScreen,
      page: () => MpinFourteenScreen(),
      bindings: [
        MpinFourteenBinding(),
      ],
    ),
    GetPage(
      name: selectBankScreen,
      page: () => SelectBankScreen(),
      bindings: [
        SelectBankBinding(),
      ],
    ),
    GetPage(
      name: businessDetailsIndividualTenScreen,
      page: () => BusinessDetailsIndividualTenScreen(),
      bindings: [
        BusinessDetailsIndividualTenBinding(),
      ],
    ),
    GetPage(
      name: scanQrSixScreen,
      page: () => ScanQrSixScreen(),
      bindings: [
        ScanQrSixBinding(),
      ],
    ),
    GetPage(
      name: notificationThreeScreen,
      page: () => NotificationThreeScreen(),
      bindings: [
        NotificationThreeBinding(),
      ],
    ),
    GetPage(
      name: notificationFiveScreen,
      page: () => NotificationFiveScreen(),
      bindings: [
        NotificationFiveBinding(),
      ],
    ),
    GetPage(
      name: ifscCodeSearchOneScreen,
      page: () => IfscCodeSearchOneScreen(),
      bindings: [
        IfscCodeSearchOneBinding(),
      ],
    ),
    GetPage(
      name: currentAccountPopUsScreen,
      page: () => CurrentAccountPopUsScreen(),
      bindings: [
        CurrentAccountPopUsBinding(),
      ],
    ),
    GetPage(
      name: odPopUpScreen,
      page: () => OdPopUpScreen(),
      bindings: [
        OdPopUpBinding(),
      ],
    ),
    GetPage(
      name: posDevicePopUpScreen,
      page: () => PosDevicePopUpScreen(),
      bindings: [
        PosDevicePopUpBinding(),
      ],
    ),
    GetPage(
      name: completeSuitPopUpScreen,
      page: () => CompleteSuitPopUpScreen(),
      bindings: [
        CompleteSuitPopUpBinding(),
      ],
    ),
    GetPage(
      name: chooseSimEightScreen,
      page: () => ChooseSimEightScreen(),
      bindings: [
        ChooseSimEightBinding(),
      ],
    ),
    GetPage(
      name: setUpiFourScreen,
      page: () => SetUpiFourScreen(),
      bindings: [
        SetUpiFourBinding(),
      ],
    ),
    GetPage(
      name: applyPosScreen,
      page: () => ApplyPosScreen(),
      bindings: [
        ApplyPosBinding(),
      ],
    ),
    GetPage(
      name: allInOneQrScreen,
      page: () => AllInOneQrScreen(),
      bindings: [
        AllInOneQrBinding(),
      ],
    ),
    GetPage(
      name: tapOnPhoneScreen,
      page: () => TapOnPhoneScreen(),
      bindings: [
        TapOnPhoneBinding(),
      ],
    ),
    GetPage(
      name: cardWithDifferentCassScreen,
      page: () => CardWithDifferentCassScreen(),
      bindings: [
        CardWithDifferentCassBinding(),
      ],
    ),
    GetPage(
      name: principleDetailsChnageAddressTwoScreen,
      page: () => PrincipleDetailsChnageAddressTwoScreen(),
      bindings: [
        PrincipleDetailsChnageAddressTwoBinding(),
      ],
    ),
    GetPage(
      name: aadharVerificationScreen,
      page: () => AadharVerificationScreen(),
      bindings: [
        AadharVerificationBinding(),
      ],
    ),
    GetPage(
      name: otpScreen,
      page: () => OtpScreen(),
      bindings: [
        OtpBinding(),
      ],
    ),
    GetPage(
      name: principleDetailsChnageAddressOneScreen,
      page: () => PrincipleDetailsChnageAddressOneScreen(),
      bindings: [
        PrincipleDetailsChnageAddressOneBinding(),
      ],
    ),
    GetPage(
      name: finalCongratsScreen,
      page: () => FinalCongratsScreen(),
      bindings: [
        FinalCongratsBinding(),
      ],
    ),
    GetPage(
      name: error1Screen,
      page: () => Error1Screen(),
      bindings: [
        Error1Binding(),
      ],
    ),
    GetPage(
      name: businessDetailsSoleProprietorFiveScreen,
      page: () => BusinessDetailsSoleProprietorFiveScreen(),
      bindings: [
        BusinessDetailsSoleProprietorFiveBinding(),
      ],
    ),
    GetPage(
      name: businessDetailsPrivateLimitedFourScreen,
      page: () => BusinessDetailsPrivateLimitedFourScreen(),
      bindings: [
        BusinessDetailsPrivateLimitedFourBinding(),
      ],
    ),
    GetPage(
      name: mpinThirteenScreen,
      page: () => MpinThirteenScreen(),
      bindings: [
        MpinThirteenBinding(),
      ],
    ),
    GetPage(
      name: mpinFifteenScreen,
      page: () => MpinFifteenScreen(),
      bindings: [
        MpinFifteenBinding(),
      ],
    ),
    GetPage(
      name: ifscCodeSearchScreen,
      page: () => IfscCodeSearchScreen(),
      bindings: [
        IfscCodeSearchBinding(),
      ],
    ),
    GetPage(
      name: selectBankTwoScreen,
      page: () => SelectBankTwoScreen(),
      bindings: [
        SelectBankTwoBinding(),
      ],
    ),
    GetPage(
      name: guestDashboardTwoScreen,
      page: () => GuestDashboardTwoScreen(),
      bindings: [
        GuestDashboardTwoBinding(),
      ],
    ),
    GetPage(
      name: businessDetailsIndividualNineScreen,
      page: () => BusinessDetailsIndividualNineScreen(),
      bindings: [
        BusinessDetailsIndividualNineBinding(),
      ],
    ),
    GetPage(
      name: chooseSimSevenScreen,
      page: () => ChooseSimSevenScreen(),
      bindings: [
        ChooseSimSevenBinding(),
      ],
    ),
    GetPage(
      name: chooseSimSixScreen,
      page: () => ChooseSimSixScreen(),
      bindings: [
        ChooseSimSixBinding(),
      ],
    ),
    GetPage(
      name: rewardsScreen,
      page: () => RewardsScreen(),
      bindings: [
        RewardsBinding(),
      ],
    ),
    GetPage(
      name: withLoginUsingIciciCredentialsScreen,
      page: () => WithLoginUsingIciciCredentialsScreen(),
      bindings: [
        WithLoginUsingIciciCredentialsBinding(),
      ],
    ),
    GetPage(
      name: mpinLoginUncheckedScreen,
      page: () => MpinLoginUncheckedScreen(),
      bindings: [
        MpinLoginUncheckedBinding(),
      ],
    ),
    GetPage(
      name: mpinLoginUncheckedOneScreen,
      page: () => MpinLoginUncheckedOneScreen(),
      bindings: [
        MpinLoginUncheckedOneBinding(),
      ],
    ),
    GetPage(
      name: businessDetailsIndividualElevenScreen,
      page: () => BusinessDetailsIndividualElevenScreen(),
      bindings: [
        BusinessDetailsIndividualElevenBinding(),
      ],
    ),
    GetPage(
      name: mpinEighteenScreen,
      page: () => MpinEighteenScreen(),
      bindings: [
        MpinEighteenBinding(),
      ],
    ),
    GetPage(
      name: mpinTwentytwoScreen,
      page: () => MpinTwentytwoScreen(),
      bindings: [
        MpinTwentytwoBinding(),
      ],
    ),
    GetPage(
      name: ifscCodeSearchTwoScreen,
      page: () => IfscCodeSearchTwoScreen(),
      bindings: [
        IfscCodeSearchTwoBinding(),
      ],
    ),
    GetPage(
      name: bankNameAutoPopulatedScreen,
      page: () => BankNameAutoPopulatedScreen(),
      bindings: [
        BankNameAutoPopulatedBinding(),
      ],
    ),
    GetPage(
      name: enterAccountDetailsOtherBanksOneScreen,
      page: () => EnterAccountDetailsOtherBanksOneScreen(),
      bindings: [
        EnterAccountDetailsOtherBanksOneBinding(),
      ],
    ),
    GetPage(
      name: frame1888Screen,
      page: () => Frame1888Screen(),
      bindings: [
        Frame1888Binding(),
      ],
    ),
    GetPage(
      name: frame1948Screen,
      page: () => Frame1948Screen(),
      bindings: [
        Frame1948Binding(),
      ],
    ),
    GetPage(
      name: aadharVerification1Screen,
      page: () => AadharVerification1Screen(),
      bindings: [
        AadharVerification1Binding(),
      ],
    ),
    GetPage(
      name: aadharAddedScreen,
      page: () => AadharAddedScreen(),
      bindings: [
        AadharAddedBinding(),
      ],
    ),
    GetPage(
      name: otp1Screen,
      page: () => Otp1Screen(),
      bindings: [
        Otp1Binding(),
      ],
    ),
    GetPage(
      name: principleDetailsChnageAddressThreeScreen,
      page: () => PrincipleDetailsChnageAddressThreeScreen(),
      bindings: [
        PrincipleDetailsChnageAddressThreeBinding(),
      ],
    ),
    GetPage(
      name: finalCongratsScreenOneScreen,
      page: () => FinalCongratsScreenOneScreen(),
      bindings: [
        FinalCongratsScreenOneBinding(),
      ],
    ),
    GetPage(
      name: error2Screen,
      page: () => Error2Screen(),
      bindings: [
        Error2Binding(),
      ],
    ),
    GetPage(
      name: skipPopUpScreen,
      page: () => SkipPopUpScreen(),
      bindings: [
        SkipPopUpBinding(),
      ],
    ),
    GetPage(
      name: verifyMobileNoTwoScreen,
      page: () => VerifyMobileNoTwoScreen(),
      bindings: [
        VerifyMobileNoTwoBinding(),
      ],
    ),
    GetPage(
      name: verifyingMobileElevenScreen,
      page: () => VerifyingMobileElevenScreen(),
      bindings: [
        VerifyingMobileElevenBinding(),
      ],
    ),
    GetPage(
      name: verifyingMobileEightScreen,
      page: () => VerifyingMobileEightScreen(),
      bindings: [
        VerifyingMobileEightBinding(),
      ],
    ),
    GetPage(
      name: verifyingMobileTenScreen,
      page: () => VerifyingMobileTenScreen(),
      bindings: [
        VerifyingMobileTenBinding(),
      ],
    ),
    GetPage(
      name: mpinTwentyScreen,
      page: () => MpinTwentyScreen(),
      bindings: [
        MpinTwentyBinding(),
      ],
    ),
    GetPage(
      name: mpinSetThreeScreen,
      page: () => MpinSetThreeScreen(),
      bindings: [
        MpinSetThreeBinding(),
      ],
    ),
    GetPage(
      name: guestLandingPageThreeScreen,
      page: () => GuestLandingPageThreeScreen(),
      bindings: [
        GuestLandingPageThreeBinding(),
      ],
    ),
    GetPage(
      name: businessDetailsIndividualFourteenScreen,
      page: () => BusinessDetailsIndividualFourteenScreen(),
      bindings: [
        BusinessDetailsIndividualFourteenBinding(),
      ],
    ),
    GetPage(
      name: scanQrSevenScreen,
      page: () => ScanQrSevenScreen(),
      bindings: [
        ScanQrSevenBinding(),
      ],
    ),
    GetPage(
      name: businessDetailsSoleProprietorSixScreen,
      page: () => BusinessDetailsSoleProprietorSixScreen(),
      bindings: [
        BusinessDetailsSoleProprietorSixBinding(),
      ],
    ),
    GetPage(
      name: businessDetailsPrivateLimitedSevenScreen,
      page: () => BusinessDetailsPrivateLimitedSevenScreen(),
      bindings: [
        BusinessDetailsPrivateLimitedSevenBinding(),
      ],
    ),
    GetPage(
      name: mpinTwentythreeScreen,
      page: () => MpinTwentythreeScreen(),
      bindings: [
        MpinTwentythreeBinding(),
      ],
    ),
    GetPage(
      name: businessDetailsIndividualThirteenScreen,
      page: () => BusinessDetailsIndividualThirteenScreen(),
      bindings: [
        BusinessDetailsIndividualThirteenBinding(),
      ],
    ),
    GetPage(
      name: scanQrEightScreen,
      page: () => ScanQrEightScreen(),
      bindings: [
        ScanQrEightBinding(),
      ],
    ),
    GetPage(
      name: mpinSeventeenScreen,
      page: () => MpinSeventeenScreen(),
      bindings: [
        MpinSeventeenBinding(),
      ],
    ),
    GetPage(
      name: mpinTwentyoneScreen,
      page: () => MpinTwentyoneScreen(),
      bindings: [
        MpinTwentyoneBinding(),
      ],
    ),
    GetPage(
      name: chooseSimTenScreen,
      page: () => ChooseSimTenScreen(),
      bindings: [
        ChooseSimTenBinding(),
      ],
    ),
    GetPage(
      name: businessDetailsSoleProprietorSevenScreen,
      page: () => BusinessDetailsSoleProprietorSevenScreen(),
      bindings: [
        BusinessDetailsSoleProprietorSevenBinding(),
      ],
    ),
    GetPage(
      name: businessDetailsPrivateLimitedSixScreen,
      page: () => BusinessDetailsPrivateLimitedSixScreen(),
      bindings: [
        BusinessDetailsPrivateLimitedSixBinding(),
      ],
    ),
    GetPage(
      name: documentUploadLandingScreen,
      page: () => DocumentUploadLandingScreen(),
      bindings: [
        DocumentUploadLandingBinding(),
      ],
    ),
    GetPage(
      name: mpinSixteenScreen,
      page: () => MpinSixteenScreen(),
      bindings: [
        MpinSixteenBinding(),
      ],
    ),
    GetPage(
      name: mpinNineteenScreen,
      page: () => MpinNineteenScreen(),
      bindings: [
        MpinNineteenBinding(),
      ],
    ),
    GetPage(
      name: businessDetailsIndividualTwelveScreen,
      page: () => BusinessDetailsIndividualTwelveScreen(),
      bindings: [
        BusinessDetailsIndividualTwelveBinding(),
      ],
    ),
    GetPage(
      name: chooseSimNineScreen,
      page: () => ChooseSimNineScreen(),
      bindings: [
        ChooseSimNineBinding(),
      ],
    ),
    GetPage(
      name: chooseSimElevenScreen,
      page: () => ChooseSimElevenScreen(),
      bindings: [
        ChooseSimElevenBinding(),
      ],
    ),
    GetPage(
      name: businessDetailsIndividualFifteenScreen,
      page: () => BusinessDetailsIndividualFifteenScreen(),
      bindings: [
        BusinessDetailsIndividualFifteenBinding(),
      ],
    ),
    GetPage(
      name: error3Screen,
      page: () => Error3Screen(),
      bindings: [
        Error3Binding(),
      ],
    ),
    GetPage(
      name: gstinDetailsScreen,
      page: () => GstinDetailsScreen(),
      bindings: [
        GstinDetailsBinding(),
      ],
    ),
    GetPage(
      name: gstinAddedScreen,
      page: () => GstinAddedScreen(),
      bindings: [
        GstinAddedBinding(),
      ],
    ),
    GetPage(
      name: finalSuccessScreen,
      page: () => FinalSuccessScreen(),
      bindings: [
        FinalSuccessBinding(),
      ],
    ),
    GetPage(
      name: personalDetailsOneScreen,
      page: () => PersonalDetailsOneScreen(),
      bindings: [
        PersonalDetailsOneBinding(),
      ],
    ),
    GetPage(
      name: personalDetailsTwoScreen,
      page: () => PersonalDetailsTwoScreen(),
      bindings: [
        PersonalDetailsTwoBinding(),
      ],
    ),
    GetPage(
      name: verifyMobileNoThreeScreen,
      page: () => VerifyMobileNoThreeScreen(),
      bindings: [
        VerifyMobileNoThreeBinding(),
      ],
    ),
    GetPage(
      name: verifyingMobileNineScreen,
      page: () => VerifyingMobileNineScreen(),
      bindings: [
        VerifyingMobileNineBinding(),
      ],
    ),
    GetPage(
      name: verifyingMobileSevenScreen,
      page: () => VerifyingMobileSevenScreen(),
      bindings: [
        VerifyingMobileSevenBinding(),
      ],
    ),
    GetPage(
      name: verifyingMobileSixScreen,
      page: () => VerifyingMobileSixScreen(),
      bindings: [
        VerifyingMobileSixBinding(),
      ],
    ),
    GetPage(
      name: mpinNineScreen,
      page: () => MpinNineScreen(),
      bindings: [
        MpinNineBinding(),
      ],
    ),
    GetPage(
      name: mpinTwoScreen,
      page: () => MpinTwoScreen(),
      bindings: [
        MpinTwoBinding(),
      ],
    ),
    GetPage(
      name: mpinOneScreen,
      page: () => MpinOneScreen(),
      bindings: [
        MpinOneBinding(),
      ],
    ),
    GetPage(
      name: mpinSetOneScreen,
      page: () => MpinSetOneScreen(),
      bindings: [
        MpinSetOneBinding(),
      ],
    ),
    GetPage(
      name: guestLandingPageOneScreen,
      page: () => GuestLandingPageOneScreen(),
      bindings: [
        GuestLandingPageOneBinding(),
      ],
    ),
    GetPage(
      name: businessDetailsIndividualOneScreen,
      page: () => BusinessDetailsIndividualOneScreen(),
      bindings: [
        BusinessDetailsIndividualOneBinding(),
      ],
    ),
    GetPage(
      name: scanQrFourScreen,
      page: () => ScanQrFourScreen(),
      bindings: [
        ScanQrFourBinding(),
      ],
    ),
    GetPage(
      name: businessDetailsSoleProprietorTwoScreen,
      page: () => BusinessDetailsSoleProprietorTwoScreen(),
      bindings: [
        BusinessDetailsSoleProprietorTwoBinding(),
      ],
    ),
    GetPage(
      name: businessDetailsPrivateLimitedOneScreen,
      page: () => BusinessDetailsPrivateLimitedOneScreen(),
      bindings: [
        BusinessDetailsPrivateLimitedOneBinding(),
      ],
    ),
    GetPage(
      name: gstinDetailsMissingScreen,
      page: () => GstinDetailsMissingScreen(),
      bindings: [
        GstinDetailsMissingBinding(),
      ],
    ),
    GetPage(
      name: mpinFiveScreen,
      page: () => MpinFiveScreen(),
      bindings: [
        MpinFiveBinding(),
      ],
    ),
    GetPage(
      name: mpinSixScreen,
      page: () => MpinSixScreen(),
      bindings: [
        MpinSixBinding(),
      ],
    ),
    GetPage(
      name: mpinTenScreen,
      page: () => MpinTenScreen(),
      bindings: [
        MpinTenBinding(),
      ],
    ),
    GetPage(
      name: businessDetailsIndividualFourScreen,
      page: () => BusinessDetailsIndividualFourScreen(),
      bindings: [
        BusinessDetailsIndividualFourBinding(),
      ],
    ),
    GetPage(
      name: scanQrOneScreen,
      page: () => ScanQrOneScreen(),
      bindings: [
        ScanQrOneBinding(),
      ],
    ),
    GetPage(
      name: chooseSimThreeScreen,
      page: () => ChooseSimThreeScreen(),
      bindings: [
        ChooseSimThreeBinding(),
      ],
    ),
    GetPage(
      name: businessDetailsSoleProprietorFourScreen,
      page: () => BusinessDetailsSoleProprietorFourScreen(),
      bindings: [
        BusinessDetailsSoleProprietorFourBinding(),
      ],
    ),
    GetPage(
      name: businessDetailsPrivateLimitedTwoScreen,
      page: () => BusinessDetailsPrivateLimitedTwoScreen(),
      bindings: [
        BusinessDetailsPrivateLimitedTwoBinding(),
      ],
    ),
    GetPage(
      name: businessDetailsIndividualFiveScreen,
      page: () => BusinessDetailsIndividualFiveScreen(),
      bindings: [
        BusinessDetailsIndividualFiveBinding(),
      ],
    ),
    GetPage(
      name: chooseSimTwoScreen,
      page: () => ChooseSimTwoScreen(),
      bindings: [
        ChooseSimTwoBinding(),
      ],
    ),
    GetPage(
      name: chooseSimFiveScreen,
      page: () => ChooseSimFiveScreen(),
      bindings: [
        ChooseSimFiveBinding(),
      ],
    ),
    GetPage(
      name: businessDetailsIndividualSevenScreen,
      page: () => BusinessDetailsIndividualSevenScreen(),
      bindings: [
        BusinessDetailsIndividualSevenBinding(),
      ],
    ),
    GetPage(
      name: verifyMobileNoOneScreen,
      page: () => VerifyMobileNoOneScreen(),
      bindings: [
        VerifyMobileNoOneBinding(),
      ],
    ),
    GetPage(
      name: verifyingMobileThreeScreen,
      page: () => VerifyingMobileThreeScreen(),
      bindings: [
        VerifyingMobileThreeBinding(),
      ],
    ),
    GetPage(
      name: verifyingMobileFourScreen,
      page: () => VerifyingMobileFourScreen(),
      bindings: [
        VerifyingMobileFourBinding(),
      ],
    ),
    GetPage(
      name: verifyingMobileFiveScreen,
      page: () => VerifyingMobileFiveScreen(),
      bindings: [
        VerifyingMobileFiveBinding(),
      ],
    ),
    GetPage(
      name: mpinEightScreen,
      page: () => MpinEightScreen(),
      bindings: [
        MpinEightBinding(),
      ],
    ),
    GetPage(
      name: mpinFourScreen,
      page: () => MpinFourScreen(),
      bindings: [
        MpinFourBinding(),
      ],
    ),
    GetPage(
      name: mpinSevenScreen,
      page: () => MpinSevenScreen(),
      bindings: [
        MpinSevenBinding(),
      ],
    ),
    GetPage(
      name: mpinSetTwoScreen,
      page: () => MpinSetTwoScreen(),
      bindings: [
        MpinSetTwoBinding(),
      ],
    ),
    GetPage(
      name: guestLandingPageTwoScreen,
      page: () => GuestLandingPageTwoScreen(),
      bindings: [
        GuestLandingPageTwoBinding(),
      ],
    ),
    GetPage(
      name: businessDetailsIndividualThreeScreen,
      page: () => BusinessDetailsIndividualThreeScreen(),
      bindings: [
        BusinessDetailsIndividualThreeBinding(),
      ],
    ),
    GetPage(
      name: scanQrTwoScreen,
      page: () => ScanQrTwoScreen(),
      bindings: [
        ScanQrTwoBinding(),
      ],
    ),
    GetPage(
      name: businessDetailsSoleProprietorThreeScreen,
      page: () => BusinessDetailsSoleProprietorThreeScreen(),
      bindings: [
        BusinessDetailsSoleProprietorThreeBinding(),
      ],
    ),
    GetPage(
      name: businessDetailsPrivateLimitedScreen,
      page: () => BusinessDetailsPrivateLimitedScreen(),
      bindings: [
        BusinessDetailsPrivateLimitedBinding(),
      ],
    ),
    GetPage(
      name: mpinElevenScreen,
      page: () => MpinElevenScreen(),
      bindings: [
        MpinElevenBinding(),
      ],
    ),
    GetPage(
      name: mpinTwelveScreen,
      page: () => MpinTwelveScreen(),
      bindings: [
        MpinTwelveBinding(),
      ],
    ),
    GetPage(
      name: mpinThreeScreen,
      page: () => MpinThreeScreen(),
      bindings: [
        MpinThreeBinding(),
      ],
    ),
    GetPage(
      name: businessDetailsIndividualSixScreen,
      page: () => BusinessDetailsIndividualSixScreen(),
      bindings: [
        BusinessDetailsIndividualSixBinding(),
      ],
    ),
    GetPage(
      name: scanQrThreeScreen,
      page: () => ScanQrThreeScreen(),
      bindings: [
        ScanQrThreeBinding(),
      ],
    ),
    GetPage(
      name: chooseSimOneScreen,
      page: () => ChooseSimOneScreen(),
      bindings: [
        ChooseSimOneBinding(),
      ],
    ),
    GetPage(
      name: businessDetailsSoleProprietorOneScreen,
      page: () => BusinessDetailsSoleProprietorOneScreen(),
      bindings: [
        BusinessDetailsSoleProprietorOneBinding(),
      ],
    ),
    GetPage(
      name: businessDetailsPrivateLimitedThreeScreen,
      page: () => BusinessDetailsPrivateLimitedThreeScreen(),
      bindings: [
        BusinessDetailsPrivateLimitedThreeBinding(),
      ],
    ),
    GetPage(
      name: businessDetailsIndividualEightScreen,
      page: () => BusinessDetailsIndividualEightScreen(),
      bindings: [
        BusinessDetailsIndividualEightBinding(),
      ],
    ),
    GetPage(
      name: chooseSimFourScreen,
      page: () => ChooseSimFourScreen(),
      bindings: [
        ChooseSimFourBinding(),
      ],
    ),
    GetPage(
      name: chooseSimScreen,
      page: () => ChooseSimScreen(),
      bindings: [
        ChooseSimBinding(),
      ],
    ),
    GetPage(
      name: businessDetailsIndividualTwoScreen,
      page: () => BusinessDetailsIndividualTwoScreen(),
      bindings: [
        BusinessDetailsIndividualTwoBinding(),
      ],
    ),
    GetPage(
      name: appNavigationScreen,
      page: () => AppNavigationScreen(),
      bindings: [
        AppNavigationBinding(),
      ],
    ),
    GetPage(
      name: initialRoute,
      page: () => AndroidSmallThreeScreen(),
      bindings: [
        AndroidSmallThreeBinding(),
      ],
    )
  ];
}
